import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { chromium } from "@playwright/test";
import { createPostgresHarness } from "../integration/postgres-harness.js";
import { readMigrationFiles, runMigrations } from "../../packages/persistence/src/migrations.js";
import { bootstrapPracticeAdmin } from "../../apps/api/src/auth/bootstrap.js";
import { createApiServer } from "../../apps/api/src/server.js";

const browser=await chromium.launch();
const harness=await createPostgresHarness().catch(async error=>{await browser.close();throw error;});
const server=createApiServer({pool:harness.pool});
try{
 await runMigrations(harness.pool,await readMigrationFiles("migrations"));
 const password=randomBytes(24).toString("base64url");
 await bootstrapPracticeAdmin(harness.pool,{email:"delivery@example.test",displayName:"Delivery Lead",password});
 await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));
 const address=server.address();assert(address&&typeof address!=="string");const base=`http://127.0.0.1:${address.port}`;
 const page=await browser.newPage({viewport:{width:1400,height:1000}});page.setDefaultTimeout(15000);const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
 await page.goto(base);await page.getByLabel("Email",{exact:true}).fill("delivery@example.test");await page.getByLabel("Password",{exact:true}).fill(password);await page.getByRole("button",{name:"Sign in",exact:true}).click();await page.getByRole("button",{name:"Sample data",exact:true}).waitFor();
 assert.equal((await page.request.post(base+"/api/samples/load",{data:{expectedRevision:0,requestKey:randomUUID(),confirmation:"load-sample-data"}})).status(),200);
 const engagement=(await(await page.request.get(base+"/api/engagements")).json()).engagements.find((e:{title:string})=>e.title.includes("apprenticeship"));assert(engagement);
 const initialDelivery=await page.request.get(`${base}/api/engagements/${engagement.id}/delivery`);assert.equal(initialDelivery.status(),200,await initialDelivery.text());
 await page.reload();await page.getByRole("button",{name:engagement.title,exact:true}).click();await page.getByRole("heading",{name:"Delivery tracking",exact:true}).waitFor();
 const nav=page.getByRole("navigation",{name:"Delivery tracking sections"});await nav.waitFor();assert.equal(await nav.getByRole("button").count(),6);
 const current=()=>page.locator(".delivery-panels > section:not([hidden])");
 await current().locator("summary").filter({hasText:"Propose a new scope version"}).click();await current().getByLabel("Estimate",{exact:true}).fill("Four-week delivery window");await current().getByLabel("Commitments, one per line").fill("Configured workspace\nOperator handover");await current().getByLabel("Out of scope, one per line").fill("Custom integrations");await current().getByLabel("Acceptance criteria, one per line").fill("Named operator can complete the workflow");await current().getByRole("button",{name:"Propose scope"}).click();await page.getByText("Scope proposal added.",{exact:true}).waitFor();
 await current().locator("summary").filter({hasText:"Review this proposal"}).click();await current().getByLabel("Rationale",{exact:true}).fill("The proposal reflects the agreed delivery boundary.");await current().getByRole("button",{name:"Record decision",exact:true}).click();await page.getByText("Scope decision recorded.",{exact:true}).waitFor();
 await nav.getByRole("button",{name:/Milestones/}).click();await current().locator("summary").filter({hasText:"Add milestone"}).click();await current().getByLabel("Title",{exact:true}).fill("Operator walkthrough");await current().getByLabel("Due date",{exact:true}).fill("2026-10-15");await current().getByRole("button",{name:"Add milestone",exact:true}).click();await page.getByText("Milestone added.",{exact:true}).waitFor();
 let delivery=(await(await page.request.get(`${base}/api/engagements/${engagement.id}/delivery`)).json()).delivery;const milestone=delivery.milestones[0];assert(milestone);
 assert.equal((await page.request.post(`${base}/api/engagements/${engagement.id}/delivery/milestones/${milestone.id}`,{data:{requestKey:randomUUID(),expectedRevision:milestone.revision,status:"in_progress"}})).status(),200);
 assert.equal((await page.request.post(`${base}/api/engagements/${engagement.id}/delivery/milestones/${milestone.id}`,{data:{requestKey:randomUUID(),expectedRevision:milestone.revision,status:"complete"}})).status(),409);
 await Promise.all([page.waitForResponse(response=>response.url().endsWith(`/api/engagements/${engagement.id}/delivery`)&&response.status()===200),page.locator(".delivery-work").getByRole("button",{name:"Refresh",exact:true}).click()]);await current().locator("summary").filter({hasText:"Edit milestone"}).click();await current().locator('select[name="status"]:visible').selectOption("complete");await current().getByRole("button",{name:"Save milestone"}).click();await page.getByText("Milestone updated.",{exact:true}).waitFor();
 await nav.getByRole("button",{name:/Risks/}).click();await current().locator("summary").filter({hasText:"Add risk"}).click();await current().getByLabel("Title",{exact:true}).fill("Delayed stakeholder response");await current().locator('select[name="severity"]:visible').selectOption("high");await current().getByLabel("Mitigation",{exact:true}).fill("Confirm deputies and escalation path.");await current().getByRole("button",{name:"Add risk",exact:true}).click();await page.getByText("Risk added.",{exact:true}).waitFor();
 await nav.getByRole("button",{name:/Decisions/}).click();await current().locator("summary").filter({hasText:"Record decision"}).click();await current().getByLabel("Title",{exact:true}).fill("Use weekly checkpoints");await current().getByLabel("Decision",{exact:true}).fill("Review progress each Friday.");await current().getByLabel("Rationale",{exact:true}).fill("A weekly cadence keeps owners aligned.");await current().getByRole("button",{name:"Record decision",exact:true}).click();await page.getByText("Decision recorded.",{exact:true}).waitFor();
 await nav.getByRole("button",{name:/Deliverables/}).click();await current().locator("summary").filter({hasText:"Add deliverable"}).click();await current().getByLabel("Title",{exact:true}).fill("Operator guide");await current().getByLabel("Description",{exact:true}).fill("A concise operating and handover guide.");await current().getByRole("button",{name:"Add deliverable",exact:true}).click();await page.getByText("Deliverable added.",{exact:true}).waitFor();
 await nav.getByRole("button",{name:/Follow-ups/}).click();await current().locator("summary").filter({hasText:"Record acceptance"}).click();await current().locator('select[name="deliverableId"]:visible').selectOption({label:"Operator guide"});await current().locator('select[name="result"]:visible').selectOption("accepted");await current().getByLabel("Rationale",{exact:true}).fill("Internal review completed successfully.");await current().getByRole("button",{name:"Record acceptance",exact:true}).click();await page.getByText("Acceptance recorded.",{exact:true}).waitFor();
 await current().locator("summary").filter({hasText:"Add follow-up"}).click();await current().getByLabel("Title",{exact:true}).fill("Schedule thirty-day review");await current().getByRole("button",{name:"Add follow-up",exact:true}).click();await page.getByText("Follow-up added.",{exact:true}).waitFor();
 await page.reload();await page.getByRole("button",{name:engagement.title,exact:true}).click();await page.getByRole("heading",{name:"Delivery tracking",exact:true}).waitFor();for(const name of ["Operator walkthrough","Delayed stakeholder response","Use weekly checkpoints","Operator guide"]){await nav.getByRole("button",{name:name==="Operator walkthrough"?/Milestones/:name==="Delayed stakeholder response"?/Risks/:name==="Use weekly checkpoints"?/Decisions/:/Deliverables/}).click();await page.getByRole("heading",{name,exact:true}).waitFor();}
 delivery=(await(await page.request.get(`${base}/api/engagements/${engagement.id}/delivery`)).json()).delivery;assert.equal(delivery.scopes[0].state,"accepted");assert.equal(delivery.milestones[0].status,"complete");assert.equal(delivery.acceptance[0].sourceType,"internal");assert.equal(delivery.followups[0].title,"Schedule thirty-day review");
 const readouts=page.locator(".final-readouts");await readouts.locator("summary").filter({hasText:"Generate a readout"}).click();await readouts.getByLabel("Readout title").fill("Delivery handover");await readouts.getByRole("button",{name:"Generate snapshot"}).click();await readouts.getByRole("heading",{name:"Delivery handover",exact:true}).first().waitFor();await readouts.getByLabel("Readout preview").getByText(/Delivery handover/).first().waitFor();
 let readoutList=(await(await page.request.get(`${base}/api/engagements/${engagement.id}/readouts`)).json()).readouts;const firstReadout=readoutList.find((item:{title:string})=>item.title==="Delivery handover");assert(firstReadout);for(const format of ["markdown","json"]){const download=await page.request.get(`${base}/api/engagements/${engagement.id}/readouts/${firstReadout.id}/${format}`);assert.equal(download.status(),200);assert.match(download.headers()["content-disposition"]??"",/attachment/i);}
 await readouts.locator("summary").filter({hasText:"Review this readout"}).click();await readouts.getByLabel("Readout review rationale").fill("The delivery record is ready for handover.");await readouts.getByRole("button",{name:"Record readout review"}).click();await page.getByText("Readout saved.",{exact:true}).waitFor();
 await readouts.getByLabel("Readout title").fill("Pre-change snapshot");await readouts.getByRole("button",{name:"Generate snapshot"}).click();await readouts.getByRole("heading",{name:"Pre-change snapshot",exact:true}).first().waitFor();
 assert.equal((await page.request.post(`${base}/api/engagements/${engagement.id}/delivery/followups`,{data:{requestKey:randomUUID(),title:"Added after snapshot",ownerUserId:null,dueDate:null}})).status(),201);await readouts.getByRole("button",{name:"Refresh readouts"}).click();await readouts.getByText("The engagement changed after this snapshot.",{exact:false}).waitFor();assert.equal(await readouts.getByLabel("Readout decision").isDisabled(),true);
 const sample=(await(await page.request.get(base+"/api/samples")).json()).sample;assert.equal((await page.request.post(base+"/api/samples/remove",{data:{expectedRevision:sample.revision,requestKey:randomUUID(),confirmation:"remove-sample-data"}})).status(),200);assert.deepEqual(errors,[]);
 console.log("PASS: delivery lifecycle plus readout generation, preview, downloads, review, source-change staleness and cleanup.");
}catch(error){const page=browser.contexts()[0]?.pages()[0];if(page)console.log((await page.locator("body").innerText()).slice(-3500));throw error;}finally{await browser.close();if(server.listening)await new Promise<void>(resolve=>server.close(()=>resolve()));await harness.dispose();}
