import assert from "node:assert/strict";
import {randomBytes} from "node:crypto";
import {chromium,type Page} from "@playwright/test";
import {createPostgresHarness} from "../integration/postgres-harness.js";
import {readMigrationFiles,runMigrations} from "../../packages/persistence/src/migrations.js";
import {bootstrapPracticeAdmin} from "../../apps/api/src/auth/bootstrap.js";
import {createApiServer} from "../../apps/api/src/server.js";
const browser=await chromium.launch(),harness=await createPostgresHarness().catch(async e=>{await browser.close();throw e}),server=createApiServer({pool:harness.pool});
try{
 await runMigrations(harness.pool,await readMigrationFiles("migrations"));const password=randomBytes(24).toString("base64url");await bootstrapPracticeAdmin(harness.pool,{email:"training-admin@example.test",displayName:"Training Admin",password});await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const address=server.address();assert(address&&typeof address!=="string");const base=`http://127.0.0.1:${address.port}`;
 async function login(email:string){const page=await browser.newPage();page.setDefaultTimeout(15000);await page.goto(base);await page.getByLabel("Email",{exact:true}).fill(email);await page.getByLabel("Password",{exact:true}).fill(password);await page.getByRole("button",{name:"Sign in",exact:true}).click();await page.getByRole("button",{name:"Training",exact:true}).waitFor();await page.getByRole("button",{name:"Training",exact:true}).click();await page.getByRole("heading",{name:"Training",exact:true}).waitFor();return page}
 async function createUser(page:Page,email:string,displayName:string){const response=await page.request.post(base+"/api/v1/auth/users",{data:{email,displayName,password,role:"member"}});assert.equal(response.status(),201,await response.text());return (await response.json()).data.user.id as string}
 const admin=await login("training-admin@example.test"),learnerId=await createUser(admin,"learner@example.test","Learning Engineer"),mentorId=await createUser(admin,"mentor@example.test","Practice Mentor");
 await admin.getByRole("button",{name:"Training sets"}).click();await admin.locator(".training-author summary").click();await admin.getByLabel("Training key").fill("delivery-foundations");await admin.getByLabel("Name",{exact:true}).fill("Delivery foundations");await admin.getByLabel("Purpose").fill("Practice evidence-led delivery habits.");await admin.getByLabel("Item key").fill("read-method");await admin.getByLabel("Title",{exact:true}).fill("Read the delivery method");await admin.getByLabel("Description",{exact:true}).fill("Review the core delivery method.");await admin.getByRole("button",{name:"Add training item"}).click();const secondItem=admin.locator(".training-author fieldset").nth(1);await secondItem.getByLabel("Item key").fill("run-handover");await secondItem.getByLabel("Type").selectOption("practical");await secondItem.getByLabel("Title",{exact:true}).fill("Run a handover");await secondItem.locator('textarea').fill("Demonstrate a complete handover with evidence.");await admin.getByRole("button",{name:"Create training draft"}).click();await admin.getByText("Training draft created.",{exact:true}).waitFor();await admin.getByRole("button",{name:"Publish"}).click();await admin.getByText("Delivery foundations published.",{exact:true}).waitFor();
 await admin.getByRole("button",{name:"My learning"}).click();await admin.locator("summary").filter({hasText:"Assign training"}).click();await admin.getByLabel("Published training").selectOption("delivery-foundations::1");await admin.locator('select[name="learnerUserId"]').selectOption(learnerId);await admin.locator('select[name="mentorUserId"]').selectOption(mentorId);await admin.getByRole("button",{name:"Assign training"}).click();await admin.getByText("Training assigned.",{exact:true}).waitFor();await admin.close();
 const learner=await login("learner@example.test");assert.equal(await learner.locator(".training-author").count(),0);await learner.locator("button.assignment").click();await learner.locator("summary").filter({hasText:"Run a handover"}).click();await learner.locator('select[name="status"]').last().selectOption("complete");await learner.getByRole("button",{name:"Save progress"}).last().click();await learner.getByRole("alert").filter({hasText:/requires evidence/i}).waitFor();await learner.locator("summary").filter({hasText:"Add evidence"}).click();await learner.getByLabel("Training item").first().selectOption("run-handover");await learner.getByLabel("Evidence title").fill("Observed handover");await learner.getByLabel("Link",{exact:true}).fill("https://example.test/handover");await learner.getByRole("button",{name:"Add evidence"}).click();await learner.getByText("Evidence added.",{exact:true}).waitFor();await learner.locator('select[name="status"]').last().selectOption("complete");await learner.locator('select[name="trainingEvidenceId"]').last().selectOption({label:"Observed handover"});await learner.getByRole("button",{name:"Save progress"}).last().click();await learner.getByText("Progress updated.",{exact:true}).waitFor();
const readingDetail=learner.locator(".training-items details").filter({has:learner.locator("summary").filter({hasText:"Read the delivery method"})});await readingDetail.locator("summary").click();await readingDetail.locator('select[name="status"]').selectOption("complete");await readingDetail.getByRole("button",{name:"Save progress"}).click();await learner.getByText("Progress updated.",{exact:true}).waitFor();
 const mentor=await login("mentor@example.test");await mentor.locator("button.assignment").click();assert.equal(await mentor.getByRole("button",{name:"Save progress"}).count(),0);await mentor.locator("summary").filter({hasText:"Assess learner"}).click();await mentor.getByLabel("Assessment").selectOption("competent");await mentor.getByLabel("Rationale",{exact:true}).fill("The practical handover evidence demonstrates competence.");const firstAssessment=mentor.waitForResponse(response=>response.url().endsWith("/assessments"));await mentor.getByRole("button",{name:"Record assessment"}).click();assert.equal((await firstAssessment).status(),201);await mentor.getByText("Assessment recorded.",{exact:true}).waitFor();await mentor.close();
 await readingDetail.locator('select[name="status"]').selectOption("in_progress");await readingDetail.getByRole("button",{name:"Save progress"}).click();await learner.getByText("Progress updated.",{exact:true}).waitFor();await learner.reload();await learner.getByRole("button",{name:"Training",exact:true}).click();await learner.locator("button.assignment").click();await learner.getByText("Progress changed after this assessment",{exact:true}).waitFor();await learner.screenshot({path:"work/browser/training-desktop.png",fullPage:true});await learner.setViewportSize({width:390,height:844});assert.equal(await learner.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await learner.screenshot({path:"work/browser/training-mobile.png",fullPage:true});assert.equal((await learner.request.get(base+"/api/training/sets")).status(),200);const forbidden=await learner.request.post(base+"/api/training/sets",{data:{requestKey:crypto.randomUUID(),key:"forbidden",name:"Forbidden",purpose:"Must not create",items:[{key:"x",type:"reading",title:"X",description:"X"}]}});assert.equal(forbidden.status(),403);await learner.close();
 console.log("PASS: admin author/publish/assign, practical evidence enforcement, learner progress, mentor assessment, stale warning and non-admin protection.");
}finally{await browser.close();if(server.listening)await new Promise<void>(r=>server.close(()=>r()));await harness.dispose()}
