import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { api, ApiError, type Member } from "./api";
import "./DeliveryWork.css";

type Scope={id:string;version:number;state:"proposed"|"accepted"|"rejected";commitments:string[];exclusions:string[];estimate:string;acceptanceCriteria:string[];revision:number;proposedBy:string;createdAt:string;decidedBy?:string|null;decidedAt?:string|null;decisionRationale?:string|null};
type Milestone={id:string;title:string;status:"planned"|"in_progress"|"complete"|"cancelled";ownerUserId:string|null;dueDate:string|null;revision:number;createdAt:string};
type Risk={id:string;title:string;severity:"low"|"medium"|"high"|"critical";status:"open"|"mitigated"|"accepted"|"closed";mitigation:string;ownerUserId:string|null;revision:number;createdAt:string};
type Decision={id:string;title:string;decision:string;rationale:string;actorId:string;createdAt:string};
type Deliverable={id:string;title:string;description:string;status:"draft"|"ready"|"handed_over";revision:number;createdAt:string};
type Acceptance={id:string;deliverableId:string|null;result:"accepted"|"rejected"|"partial";rationale:string;sourceType:"internal"|"external";externalName:string|null;actorId:string;createdAt:string};
type Followup={id:string;title:string;status:"open"|"complete"|"cancelled";ownerUserId:string|null;dueDate:string|null;revision:number;createdAt:string};
type Delivery={scopes:Scope[];milestones:Milestone[];risks:Risk[];decisions:Decision[];deliverables:Deliverable[];acceptance:Acceptance[];followups:Followup[]};
type EvidenceOption={id:string;title:string;fileName?:string};
type Tab="scope"|"milestones"|"risks"|"decisions"|"deliverables"|"acceptance";

const tabs:{id:Tab;label:string;description:string}[]=[
  {id:"scope",label:"Scope",description:"What the team committed to deliver"},
  {id:"milestones",label:"Milestones",description:"Dates and progress checkpoints"},
  {id:"risks",label:"Risks",description:"Issues that could affect delivery"},
  {id:"decisions",label:"Decisions",description:"An enduring decision log"},
  {id:"deliverables",label:"Deliverables",description:"Handover items and acceptance"},
  {id:"acceptance",label:"Follow-ups",description:"Acceptance history and remaining actions"},
];
const label=(value:string)=>value.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value.length===10?`${value}T00:00:00`:value)):"No date set";
const message=(error:unknown)=>error instanceof Error?error.message:"The request failed. Please try again.";
function formData(event:FormEvent<HTMLFormElement>){event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget).entries());}
function lines(value:FormDataEntryValue|undefined){const items=String(value??"").split("\n").map(item=>item.trim()).filter(Boolean);if(items.length>100)throw new Error("Use no more than 100 entries in each scope list.");if(items.some(item=>item.length>1000))throw new Error("Each scope entry must be 1,000 characters or fewer.");return items;}

function Empty({children}:{children:ReactNode}){return <p className="delivery-empty">{children}</p>}
function OwnerSelect({members,value}:{members:Member[];value:string|null}){return <select name="ownerUserId" defaultValue={value??""}><option value="">Unassigned</option>{value&&!members.some(member=>member.userId===value)&&<option value={value} disabled>Former team member</option>}{members.map(member=><option value={member.userId} key={`${member.userId}-${member.role}`}>{member.displayName??member.email??"Team member"}</option>)}</select>}

export function DeliveryWork({engagementId}:{engagementId:string}){
  const [delivery,setDelivery]=useState<Delivery|null>(null);const [members,setMembers]=useState<Member[]>([]);const [evidence,setEvidence]=useState<EvidenceOption[]>([]);
  const [active,setActive]=useState<Tab>("scope");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [reset,setReset]=useState(0);
  const [requestKeys]=useState(()=>new Map<string,string>());
  const owners=useMemo(()=>Array.from(new Map(members.map(member=>[member.userId,member])).values()),[members]);
  async function refresh(clear=false){const [d,m,w]=await Promise.all([api<{delivery:Delivery}>(`/api/engagements/${encodeURIComponent(engagementId)}/delivery`),api<{members:Member[]}>(`/api/engagements/${encodeURIComponent(engagementId)}/members`),api<{work:{evidence:EvidenceOption[]}}>(`/api/engagements/${encodeURIComponent(engagementId)}/work`)]);setDelivery(d.delivery);setMembers(m.members);setEvidence(w.work.evidence);setError("");if(clear){setReset(value=>value+1);setNotice("");requestKeys.clear();}}
  useEffect(()=>{void refresh(true).catch(e=>setError(message(e)));},[engagementId]);
  async function mutate(url:string,payload:Record<string,unknown>,success:string){const intent=JSON.stringify([url,payload]);let requestKey=requestKeys.get(intent);if(!requestKey){requestKey=crypto.randomUUID();requestKeys.set(intent,requestKey);}setBusy(true);setError("");setNotice("");try{await api(url,{...payload,requestKey});await refresh();requestKeys.delete(intent);setNotice(success);return true;}catch(e){setError(message(e));if(e instanceof ApiError&&e.status===409)setNotice("Delivery information changed. Refresh before trying again.");return false;}finally{setBusy(false);}}
  const ownerName=(id:string|null)=>id?owners.find(member=>member.userId===id)?.displayName??"Former team member":"Unassigned";
  const actorName=(id:string|null|undefined)=>id?owners.find(member=>member.userId===id)?.displayName??"Recorded participant":"Recorded participant";
  const create=async(event:FormEvent<HTMLFormElement>,collection:string,payload:(data:Record<string,FormDataEntryValue>)=>Record<string,unknown>,success:string)=>{const form=event.currentTarget;const data=formData(event);try{if(await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/delivery/${collection}`,payload(data),success))form.reset();}catch(e){setError(message(e));}};
  const update=async(event:FormEvent<HTMLFormElement>,collection:string,id:string,revision:number,payload:(data:Record<string,FormDataEntryValue>)=>Record<string,unknown>,success:string)=>{const data=formData(event);await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/delivery/${collection}/${encodeURIComponent(id)}`,{expectedRevision:revision,...payload(data)},success);};
  if(!delivery)return <section className="delivery-work"><h2>Delivery tracking</h2>{error?<p className="error" role="alert">{error} <button onClick={()=>void refresh(true).catch(e=>setError(message(e)))}>Try again</button></p>:<p>Loading delivery information…</p>}</section>;
  return <section className="delivery-work" key={reset}>
    <header className="delivery-header"><div><p className="eyebrow">Engagement delivery</p><h2>Delivery tracking</h2><p>Keep the agreed scope, progress, decisions and handover record in one place.</p></div><button disabled={busy} onClick={()=>void refresh(true).catch(e=>setError(message(e)))}>Refresh</button></header>
    {error&&<p className="error" role="alert">{error} {notice&&<button onClick={()=>void refresh(true).catch(e=>setError(message(e)))}>Refresh now</button>}</p>}{notice&&!error&&<p className="notice" role="status">{notice}</p>}
    <nav className="delivery-tabs" aria-label="Delivery tracking sections">{tabs.map(tab=><button key={tab.id} className={active===tab.id?"selected":undefined} aria-pressed={active===tab.id} onClick={()=>setActive(tab.id)}><strong>{tab.label}</strong><small>{tab.description}</small></button>)}</nav>
    <div className="delivery-panels">
      <section hidden={active!=="scope"} aria-labelledby="delivery-scope"><PanelTitle id="delivery-scope" title="Agreed scope" detail="Scope versions preserve what was proposed and who accepted or rejected it."/>
        {delivery.scopes.length===0?<Empty>No scope has been proposed yet.</Empty>:delivery.scopes.map(scope=><article className="delivery-record scope-record" key={scope.id}><div className="record-heading"><div><p className="record-kicker">Version {scope.version}</p><h4>{scope.estimate}</h4></div><Badge value={scope.state}/></div><div className="scope-columns"><List title="Commitments" values={scope.commitments}/><List title="Out of scope" values={scope.exclusions}/><List title="Acceptance criteria" values={scope.acceptanceCriteria}/></div><p className="record-meta">Proposed by {actorName(scope.proposedBy)} · {date(scope.createdAt)}</p>{scope.decisionRationale&&<blockquote>{scope.decisionRationale}<footer>{actorName(scope.decidedBy)} · {date(scope.decidedAt)}</footer></blockquote>}{scope.state==="proposed"&&<details><summary>Review this proposal</summary><form className="delivery-form compact" onSubmit={async event=>{const data=formData(event);await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/delivery/scopes/${encodeURIComponent(scope.id)}/decision`,{expectedRevision:scope.revision,decision:data.decision,rationale:data.rationale},"Scope decision recorded.");}}><label>Decision<select name="decision" required><option value="accepted">Accept</option><option value="rejected">Reject</option></select></label><label className="wide">Rationale<textarea name="rationale" required maxLength={10000}/></label><button disabled={busy}>Record decision</button></form></details>}</article>)}
        <details className="delivery-add"><summary>Propose a new scope version</summary><form className="delivery-form" onSubmit={event=>void create(event,"scopes",data=>({estimate:String(data.estimate),commitments:lines(data.commitments),exclusions:lines(data.exclusions),acceptanceCriteria:lines(data.acceptanceCriteria)}),"Scope proposal added.")}><label>Estimate<input name="estimate" required maxLength={300}/></label><label>Commitments, one per line<textarea name="commitments" required maxLength={10000}/></label><label>Out of scope, one per line<textarea name="exclusions" maxLength={10000}/></label><label>Acceptance criteria, one per line<textarea name="acceptanceCriteria" required maxLength={10000}/></label><button disabled={busy}>Propose scope</button></form></details>
      </section>
      <section hidden={active!=="milestones"} aria-labelledby="delivery-milestones"><PanelTitle id="delivery-milestones" title="Milestones" detail="Use a small set of checkpoints that tells the team what is next."/>
        {delivery.milestones.length===0?<Empty>No milestones yet.</Empty>:<div className="delivery-list">{delivery.milestones.map(item=><article className="delivery-record" key={item.id}><div className="record-heading"><div><h4>{item.title}</h4><p>{ownerName(item.ownerUserId)} · {item.dueDate?`Due ${date(item.dueDate)}`:"No due date"}</p></div><Badge value={item.status}/></div><details><summary>Edit milestone</summary><form className="delivery-form compact" onSubmit={event=>void update(event,"milestones",item.id,item.revision,data=>({title:data.title,status:data.status,ownerUserId:data.ownerUserId||null,dueDate:data.dueDate||null}),"Milestone updated.")}><label>Title<input name="title" defaultValue={item.title} required maxLength={300}/></label><label>Status<select name="status" defaultValue={item.status}>{["planned","in_progress","complete","cancelled"].map(v=><option value={v} key={v}>{label(v)}</option>)}</select></label><label>Owner<OwnerSelect members={owners} value={item.ownerUserId}/></label><label>Due date<input type="date" name="dueDate" defaultValue={item.dueDate??""}/></label><button disabled={busy}>Save milestone</button></form></details></article>)}</div>}
        <AddSimple title="Add milestone" busy={busy} members={owners} onSubmit={event=>void create(event,"milestones",data=>({title:data.title,status:data.status,ownerUserId:data.ownerUserId||null,dueDate:data.dueDate||null}),"Milestone added.")} statuses={["planned","in_progress","complete","cancelled"]}/>
      </section>
      <section hidden={active!=="risks"} aria-labelledby="delivery-risks"><PanelTitle id="delivery-risks" title="Risks" detail="Make ownership and mitigation visible before a risk becomes an issue."/>
        {delivery.risks.length===0?<Empty>No delivery risks recorded.</Empty>:<div className="delivery-list">{delivery.risks.map(item=><article className={`delivery-record risk-${item.severity}`} key={item.id}><div className="record-heading"><div><p className="record-kicker">{label(item.severity)} risk</p><h4>{item.title}</h4><p>{ownerName(item.ownerUserId)}</p></div><Badge value={item.status}/></div><p>{item.mitigation}</p><details><summary>Edit risk</summary><form className="delivery-form compact" onSubmit={event=>void update(event,"risks",item.id,item.revision,data=>({title:data.title,severity:data.severity,status:data.status,mitigation:data.mitigation,ownerUserId:data.ownerUserId||null}),"Risk updated.")}><label>Title<input name="title" defaultValue={item.title} required maxLength={300}/></label><label>Severity<select name="severity" defaultValue={item.severity}>{["low","medium","high","critical"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Status<select name="status" defaultValue={item.status}>{["open","mitigated","accepted","closed"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Owner<OwnerSelect members={owners} value={item.ownerUserId}/></label><label className="wide">Mitigation<textarea name="mitigation" defaultValue={item.mitigation} required maxLength={10000}/></label><button disabled={busy}>Save risk</button></form></details></article>)}</div>}
        <details className="delivery-add"><summary>Add risk</summary><form className="delivery-form" onSubmit={event=>void create(event,"risks",data=>({title:data.title,severity:data.severity,status:"open",mitigation:data.mitigation,ownerUserId:data.ownerUserId||null}),"Risk added.")}><label>Title<input name="title" required maxLength={300}/></label><label>Severity<select name="severity">{["low","medium","high","critical"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Owner<OwnerSelect members={owners} value={null}/></label><label className="wide">Mitigation<textarea name="mitigation" required maxLength={10000}/></label><button disabled={busy}>Add risk</button></form></details>
      </section>
      <section hidden={active!=="decisions"} aria-labelledby="delivery-decisions"><PanelTitle id="delivery-decisions" title="Decision log" detail="Record the outcome and why it was chosen so the team does not have to reconstruct it later."/>
        {delivery.decisions.length===0?<Empty>No decisions recorded.</Empty>:<div className="timeline">{delivery.decisions.map(item=><article key={item.id}><p className="record-kicker">{date(item.createdAt)} · {actorName(item.actorId)}</p><h4>{item.title}</h4><p><strong>Decision:</strong> {item.decision}</p><p><strong>Why:</strong> {item.rationale}</p></article>)}</div>}
        <details className="delivery-add"><summary>Record decision</summary><form className="delivery-form" onSubmit={event=>void create(event,"decisions",data=>({title:data.title,decision:data.decision,rationale:data.rationale}),"Decision recorded.")}><label>Title<input name="title" required maxLength={300}/></label><label>Decision<textarea name="decision" required maxLength={10000}/></label><label className="wide">Rationale<textarea name="rationale" required maxLength={10000}/></label><button disabled={busy}>Record decision</button></form></details>
      </section>
      <section hidden={active!=="deliverables"} aria-labelledby="delivery-deliverables"><PanelTitle id="delivery-deliverables" title="Deliverables" detail="Track each handover item from draft through delivery."/>
        {delivery.deliverables.length===0?<Empty>No deliverables yet.</Empty>:<div className="delivery-list">{delivery.deliverables.map(item=><article className="delivery-record" key={item.id}><div className="record-heading"><h4>{item.title}</h4><Badge value={item.status}/></div><p>{item.description}</p><details><summary>Edit deliverable</summary><form className="delivery-form compact" onSubmit={event=>void update(event,"deliverables",item.id,item.revision,data=>({title:data.title,description:data.description,status:data.status}),"Deliverable updated.")}><label>Title<input name="title" defaultValue={item.title} required maxLength={300}/></label><label>Status<select name="status" defaultValue={item.status}>{["draft","ready","handed_over"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label className="wide">Description<textarea name="description" defaultValue={item.description} required maxLength={10000}/></label><button disabled={busy}>Save deliverable</button></form></details></article>)}</div>}
        <details className="delivery-add"><summary>Add deliverable</summary><form className="delivery-form" onSubmit={event=>void create(event,"deliverables",data=>({title:data.title,description:data.description,status:"draft"}),"Deliverable added.")}><label>Title<input name="title" required maxLength={300}/></label><label className="wide">Description<textarea name="description" required maxLength={10000}/></label><button disabled={busy}>Add deliverable</button></form></details>
      </section>
      <section hidden={active!=="acceptance"} aria-labelledby="delivery-followups"><PanelTitle id="delivery-followups" title="Acceptance and follow-ups" detail="Preserve who accepted the work and keep remaining actions visible."/>
        <div className="acceptance-layout"><div><h4>Acceptance history</h4>{delivery.acceptance.length===0?<Empty>No acceptance recorded.</Empty>:<div className="timeline">{delivery.acceptance.map(item=><article key={item.id}><div className="record-heading"><p className="record-kicker">{item.sourceType==="external"?item.externalName:"Internal review"} · {date(item.createdAt)}</p><Badge value={item.result}/></div><p>{item.rationale}</p><small>Recorded by {actorName(item.actorId)}</small></article>)}</div>}<details className="delivery-add"><summary>Record acceptance</summary><form className="delivery-form" onSubmit={event=>{const form=event.currentTarget;const data=formData(event);if(data.sourceType==="external"&&(!String(data.externalName).trim()||!String(data.evidenceId).trim())){setError("External acceptance needs the external person or organization and supporting evidence.");return;}const payload:Record<string,unknown>={result:data.result,rationale:data.rationale,sourceType:data.sourceType};if(data.deliverableId)payload.deliverableId=data.deliverableId;if(data.sourceType==="external"){payload.externalName=data.externalName;payload.evidenceId=data.evidenceId;}void (async()=>{if(await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/delivery/acceptance`,payload,"Acceptance recorded."))form.reset();})();}}><label>Deliverable<select name="deliverableId"><option value="">Whole engagement</option>{delivery.deliverables.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><label>Result<select name="result">{["accepted","partial","rejected"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Source<select name="sourceType">{["internal","external"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>External person or organization<input name="externalName" maxLength={300}/></label><label>Supporting evidence<select name="evidenceId"><option value="">None selected</option>{evidence.map(item=><option key={item.id} value={item.id}>{item.title}{item.fileName?` — ${item.fileName}`:""}</option>)}</select></label><label className="wide">Rationale<textarea name="rationale" required maxLength={10000}/></label><button disabled={busy}>Record acceptance</button></form></details></div>
        <div><h4>Follow-up actions</h4>{delivery.followups.length===0?<Empty>No follow-up actions.</Empty>:delivery.followups.map(item=><article className="delivery-record" key={item.id}><div className="record-heading"><div><h4>{item.title}</h4><p>{ownerName(item.ownerUserId)} · {item.dueDate?`Due ${date(item.dueDate)}`:"No due date"}</p></div><Badge value={item.status}/></div><details><summary>Edit follow-up</summary><form className="delivery-form compact" onSubmit={event=>void update(event,"followups",item.id,item.revision,data=>({title:data.title,status:data.status,ownerUserId:data.ownerUserId||null,dueDate:data.dueDate||null}),"Follow-up updated.")}><label>Title<input name="title" defaultValue={item.title} required maxLength={300}/></label><label>Status<select name="status" defaultValue={item.status}>{["open","complete","cancelled"].map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label><label>Owner<OwnerSelect members={owners} value={item.ownerUserId}/></label><label>Due date<input type="date" name="dueDate" defaultValue={item.dueDate??""}/></label><button disabled={busy}>Save follow-up</button></form></details></article>)}<AddSimple title="Add follow-up" busy={busy} members={owners} onSubmit={event=>void create(event,"followups",data=>({title:data.title,status:"open",ownerUserId:data.ownerUserId||null,dueDate:data.dueDate||null}),"Follow-up added.")} statuses={[]}/></div></div>
      </section>
    </div>
  </section>;
}

function PanelTitle({id,title,detail}:{id:string;title:string;detail:string}){return <header className="panel-title"><div><h3 id={id}>{title}</h3><p>{detail}</p></div></header>}
function Badge({value}:{value:string}){return <span className={`delivery-badge badge-${value}`}>{label(value)}</span>}
function List({title,values}:{title:string;values:string[]}){return <div><h5>{title}</h5>{values.length?<ul>{values.map((value,index)=><li key={`${value}-${index}`}>{value}</li>)}</ul>:<p>None recorded.</p>}</div>}
function AddSimple({title,busy,members,statuses,onSubmit}:{title:string;busy:boolean;members:Member[];statuses:string[];onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){return <details className="delivery-add"><summary>{title}</summary><form className="delivery-form" onSubmit={onSubmit}><label>Title<input name="title" required maxLength={300}/></label>{statuses.length>0&&<label>Status<select name="status">{statuses.map(value=><option value={value} key={value}>{label(value)}</option>)}</select></label>}<label>Owner<OwnerSelect members={members} value={null}/></label><label>Due date<input type="date" name="dueDate"/></label><button disabled={busy}>{title}</button></form></details>}
