import {useEffect,useState,type FormEvent} from 'react';
import {api} from './api';
type Readout={id:string;title:string;state:'draft'|'approved'|'rejected';revision:number;asOf:string;stale:boolean;reviewRationale?:string};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Could not load readouts.';
const display=(s:string)=>s.replace(/\\([\\`*_{}\[\]#|])/g,'$1').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&amp;','&');
export function FinalReadouts({engagementId}:{engagementId:string}){
 const base=`/api/engagements/${encodeURIComponent(engagementId)}/readouts`;
 const [list,setList]=useState<Readout[]>([]),[selected,setSelected]=useState<Readout|null>(null),[preview,setPreview]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [keys]=useState(()=>new Map<string,string>());
 async function select(id:string){const r=await api<{readout:Readout}>(`${base}/${id}`);const res=await fetch(`${base}/${id}/markdown`,{credentials:'same-origin',cache:'no-store'});if(!res.ok)throw Error('Could not load the report preview.');setSelected(r.readout);setPreview(await res.text());}
 async function refresh(){setList((await api<{readouts:Readout[]}>(base)).readouts);if(selected)await select(selected.id);setError('');}
 useEffect(()=>{setSelected(null);setPreview('');void api<{readouts:Readout[]}>(base).then(x=>setList(x.readouts)).catch(e=>setError(errorText(e)));},[base]);
 async function mutate(path:string,payload:Record<string,unknown>){const intent=JSON.stringify([path,payload]);let key=keys.get(intent);if(!key){key=crypto.randomUUID();keys.set(intent,key);}setBusy(true);setError('');setNotice('');try{const r=await api<{readout:Readout}>(path,{...payload,requestKey:key});keys.delete(intent);setList((await api<{readouts:Readout[]}>(base)).readouts);await select(r.readout.id);setNotice('Readout saved.');return true;}catch(e){setError(errorText(e));return false;}finally{setBusy(false);}}
 async function generate(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;if(await mutate(base,{title:new FormData(form).get('title')}))form.reset();}
 return <section className="final-readouts"><div className="page-heading"><div><h2>Final readouts</h2><p>Bring the engagement record together for review and handover.</p></div><button disabled={busy} onClick={()=>void refresh().catch(e=>setError(errorText(e)))}>Refresh readouts</button></div>
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status" className="notice">{notice}</p>}
 <details><summary>Generate a readout</summary><p>Creates a dated snapshot. Incomplete work remains visible; generating a report does not approve the engagement.</p><form onSubmit={e=>void generate(e)}><label>Readout title<input name="title" required maxLength={300} placeholder="Engagement handover readout" disabled={busy}/></label><button disabled={busy}>Generate snapshot</button></form></details>
 {list.length===0?<p>No readouts yet. Generate the first snapshot when you are ready to review the engagement.</p>:<ul>{list.map(r=><li key={r.id}><button disabled={busy} onClick={()=>void select(r.id).catch(e=>setError(errorText(e)))}>{r.title}</button> <span>{r.state} · {new Date(r.asOf).toLocaleString()} {r.stale?'· Source changed':''}</span></li>)}</ul>}
 {selected&&<article><h3>{selected.title}</h3><p>{selected.stale?'The engagement changed after this snapshot. Generate a new readout before approval.':'This snapshot matches the engagement at the last refresh.'}</p><p><a href={`${base}/${selected.id}/markdown`}>Download readable report</a> · <a href={`${base}/${selected.id}/json`}>Download structured data</a></p>
 {selected.state==='draft'&&<details key={`${selected.id}-${selected.revision}`}><summary>Review this readout</summary><p>An engagement lead, reviewer, or administrator can record a review.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate(`${base}/${selected.id}/review`,{expectedRevision:selected.revision,decision:f.get('decision'),rationale:f.get('rationale')});}}><label>Readout decision<select name="decision" disabled={busy||selected.stale}><option value="approved">Approve</option><option value="rejected">Request changes</option></select></label><label>Readout review rationale<textarea name="rationale" required maxLength={10000} disabled={busy||selected.stale}/></label><button disabled={busy||selected.stale}>Record readout review</button></form></details>}
 <div className="readout-preview" aria-label="Readout preview">{preview.split('\n').map((line,i)=>line.startsWith('### ')?<h5 key={i}>{display(line.slice(4))}</h5>:line.startsWith('## ')?<h4 key={i}>{display(line.slice(3))}</h4>:line.startsWith('# ')?<h3 key={i}>{display(line.slice(2))}</h3>:line.trim()?<p key={i}>{display(line.replace(/^\s*- /,'• '))}</p>:null)}</div></article>}
 </section>;
}
