import {useEffect,useState,type FormEvent} from "react";
import {api,ApiError,type Member} from "./api";

type ExceptionRecord={itemId:string;ownerUserId:string;ownerName:string;dueDate:string;rationale:string};
type DecisionRecord={id:string;decision:"go"|"conditional_go"|"no_go"|"reopen";rationale:string;actorId:string;actorName:string;createdAt:string;token:string;effective:boolean;exceptions:ExceptionRecord[]};
type ReadinessItem={itemId:string;itemKey:string;name:string;reason:string};
type StageReadiness={stageId:string;definitionKey:string;name:string;token:string;requiredRole:string|null;canReview:boolean;blockers:Array<ReadinessItem&{classification:string}>;waivableItems:Array<ReadinessItem&{exceptionOwnerRole:string|null}>;notApplicableItems:Array<ReadinessItem&{reason:"optional"|"waivable"}>;latestDecision:DecisionRecord|null;history:DecisionRecord[]};
type Readiness={stages:StageReadiness[]};

const decisionLabel:Record<DecisionRecord["decision"],string>={go:"Go",conditional_go:"Conditional go",no_go:"No go",reopen:"Reopened"};
const plain=(value:string|null|undefined)=>(value??"Unmapped role").replaceAll("_"," ").replaceAll("-"," ");
const message=(error:unknown)=>error instanceof Error?error.message:"The readiness request failed.";

export function ReadinessReview({engagementId}:{engagementId:string}){
  const [readiness,setReadiness]=useState<Readiness|null>(null);
  const [members,setMembers]=useState<Member[]>([]);
  const [selectedStageId,setSelectedStageId]=useState<string|null>(null);
  const [decisions,setDecisions]=useState<Record<string,"go"|"conditional_go"|"no_go"|"reopen">>({});
  const [selectedExceptions,setSelectedExceptions]=useState(()=>new Set<string>());
  const [needsRefresh,setNeedsRefresh]=useState(false);
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [formVersion,setFormVersion]=useState(0);
  const [requestKeys]=useState(()=>new Map<string,string>());

  async function refresh(reset=false){const [result,roster]=await Promise.all([api<{readiness:Readiness}>(`/api/engagements/${encodeURIComponent(engagementId)}/readiness`),api<{members:Member[]}>(`/api/engagements/${encodeURIComponent(engagementId)}/members`)]);setReadiness(result.readiness);setMembers(Array.from(new Map(roster.members.map(member=>[member.userId,member])).values()));setSelectedStageId(current=>current&&result.readiness.stages.some(stage=>stage.stageId===current)?current:result.readiness.stages.find(stage=>stage.blockers.length>0||!stage.latestDecision?.effective)?.stageId??result.readiness.stages[0]?.stageId??null);setError("");setNeedsRefresh(false);if(reset){setFormVersion(value=>value+1);setDecisions({});setSelectedExceptions(new Set());requestKeys.clear();}}
  useEffect(()=>{refresh(true).catch(error=>setError(message(error)));},[engagementId]);
  useEffect(()=>{const changed=(event:Event)=>{const detail=(event as CustomEvent<{engagementId:string;source?:string}>).detail;if(detail?.engagementId===engagementId&&detail.source!=="readiness"){setNeedsRefresh(true);setError("Checklist work changed. Refresh readiness to review the latest information before deciding.");}};window.addEventListener("shi:engagement-work-changed",changed);return()=>window.removeEventListener("shi:engagement-work-changed",changed);},[engagementId]);

  async function mutate(url:string,payload:Record<string,unknown>,success:string){const intent=JSON.stringify([url,payload]);let requestKey=requestKeys.get(intent);if(!requestKey){requestKey=crypto.randomUUID();requestKeys.set(intent,requestKey);}setBusy(true);setError("");setNotice("");try{await api(url,{...payload,requestKey});await refresh(true);requestKeys.delete(intent);setNotice(success);window.dispatchEvent(new CustomEvent("shi:engagement-work-changed",{detail:{engagementId,source:"readiness"}}));}catch(error){setError(message(error));if(error instanceof ApiError&&error.status===409)setNotice("The readiness inputs changed. Refresh and review them before deciding again.");}finally{setBusy(false);}}

  async function submitDecision(event:FormEvent<HTMLFormElement>,stage:StageReadiness){event.preventDefault();const form=new FormData(event.currentTarget);const rationale=String(form.get("rationale")??"");const decision=String(form.get("decision")) as "go"|"conditional_go"|"no_go"|"reopen";if(decision==="reopen"){await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/readiness/stages/${encodeURIComponent(stage.stageId)}/reopen`,{expectedToken:stage.token,rationale},`${stage.name} readiness was reopened.`);return;}const exceptions=decision==="conditional_go"?stage.waivableItems.filter(item=>form.get(`exception:${item.itemId}`)==="on").map(item=>({itemId:item.itemId,ownerUserId:String(form.get(`owner:${item.itemId}`)??""),dueDate:String(form.get(`due:${item.itemId}`)??""),rationale:String(form.get(`reason:${item.itemId}`)??"")})):undefined;await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/readiness/stages/${encodeURIComponent(stage.stageId)}/decisions`,{expectedToken:stage.token,decision,rationale,...(exceptions?{exceptions}:{})},`${stage.name} readiness decision recorded.`);}
  async function markNotApplicable(event:FormEvent<HTMLFormElement>,stage:StageReadiness,item:ReadinessItem){event.preventDefault();const rationale=String(new FormData(event.currentTarget).get("rationale")??"");await mutate(`/api/engagements/${encodeURIComponent(engagementId)}/readiness/items/${encodeURIComponent(item.itemId)}/not-applicable`,{expectedToken:stage.token,rationale},`${item.name} was reviewed as not applicable.`);}

  if(!readiness)return <section className="readiness-review"><h2>Readiness review</h2>{error?<p className="error" role="alert">{error} <button onClick={()=>void refresh(true).catch(error=>setError(message(error)))}>Try again</button></p>:<p>Loading readiness checks…</p>}</section>;
  return <section className="readiness-review" key={formVersion}><div className="section-heading"><div><h2>Readiness review</h2><p>Review prerequisites and record an accountable decision. Checklist progress alone does not approve a stage.</p></div><button disabled={busy} onClick={()=>void refresh(true).then(()=>setNotice("")).catch(error=>setError(message(error)))}>Refresh</button></div>
    {error&&<p className="error" role="alert">{error} {(notice||needsRefresh)&&<button onClick={()=>void refresh(true).then(()=>setNotice("")).catch(error=>setError(message(error)))}>Refresh readiness</button>}</p>}{notice&&!error&&<p className="notice" role="status">{notice}</p>}
    <nav className="readiness-tabs" aria-label="Readiness stages">{readiness.stages.map(stage=><button type="button" key={stage.stageId} aria-pressed={selectedStageId===stage.stageId} className={selectedStageId===stage.stageId?"selected":undefined} onClick={()=>setSelectedStageId(stage.stageId)}><span>{stage.name}</span><small>{stage.blockers.length===0?"No unmet prerequisites":`${stage.blockers.length} unmet`}</small></button>)}</nav>
    {readiness.stages.map(stage=>{const decision=decisions[stage.stageId]??"go";return <div className="readiness-panel" key={stage.stageId} hidden={selectedStageId!==stage.stageId}><div className="readiness-summary"><div><h3>{stage.name}</h3><p>Accountable role: {plain(stage.requiredRole)}</p></div>{stage.latestDecision&&<span className={`readiness-decision ${stage.latestDecision.effective?"current":"stale"}`}>{decisionLabel[stage.latestDecision.decision]} · {stage.latestDecision.effective?"Current":"Needs review"}</span>}</div>
      <details className="readiness-blockers" open={stage.blockers.length>0}><summary>{stage.blockers.length===0?"No unmet readiness requirements":`${stage.blockers.length} unmet readiness requirements`}</summary>{stage.blockers.length>0&&<ul>{stage.blockers.map((blocker,index)=><li key={`${blocker.itemId}:${blocker.classification}:${blocker.reason}:${index}`}><strong>{blocker.name}</strong><span>{plain(blocker.reason)}</span><small>{plain(blocker.classification)}</small></li>)}</ul>}</details>
      {stage.canReview&&stage.notApplicableItems.length>0&&<details className="not-applicable"><summary>Items eligible for reviewed not applicable</summary>{stage.notApplicableItems.map(item=><form key={item.itemId} onSubmit={event=>void markNotApplicable(event,stage,item)}><div><strong>{item.name}</strong><small>{item.reason==="optional"?"Optional for this engagement":"Explicitly waivable"}</small></div><label>Rationale<textarea name="rationale" required maxLength={4000} disabled={busy||needsRefresh}/></label><button disabled={busy||needsRefresh}>Mark not applicable</button></form>)}</details>}
      {stage.canReview?<form className="decision-form" onSubmit={event=>void submitDecision(event,stage)}><h4>Record readiness decision</h4><label>Decision<select aria-label="Decision" name="decision" value={decision} onChange={event=>setDecisions(current=>({...current,[stage.stageId]:event.target.value as typeof decision}))} disabled={busy||needsRefresh}><option value="go">Go</option><option value="conditional_go">Conditional go</option><option value="no_go">No go</option>{stage.latestDecision&&<option value="reopen">Reopen review</option>}</select></label>{decision==="conditional_go"&&<fieldset><legend>Document approved exceptions</legend>{stage.waivableItems.length===0?<p>No unmet requirements in this stage are explicitly waivable.</p>:stage.waivableItems.map(item=>{const selected=selectedExceptions.has(item.itemId);return <div className="exception-row" key={item.itemId}><label className="check"><input type="checkbox" name={`exception:${item.itemId}`} checked={selected} onChange={event=>setSelectedExceptions(current=>{const next=new Set(current);if(event.target.checked)next.add(item.itemId);else next.delete(item.itemId);return next;})} disabled={busy||needsRefresh}/>{item.name}</label><p>Exception owner role: {plain(item.exceptionOwnerRole)}</p><label>Owner<select name={`owner:${item.itemId}`} defaultValue="" required={selected} disabled={busy||needsRefresh||!selected}><option value="">Select owner</option>{members.map(member=><option key={member.userId} value={member.userId}>{member.displayName??member.email??"Team member"}</option>)}</select></label><label>Resolve by<input type="date" name={`due:${item.itemId}`} required={selected} disabled={busy||needsRefresh||!selected}/></label><label>Exception reason<textarea name={`reason:${item.itemId}`} maxLength={4000} required={selected} disabled={busy||needsRefresh||!selected}/></label></div>})}</fieldset>}<label>Decision rationale<textarea name="rationale" required maxLength={4000} disabled={busy||needsRefresh}/></label><button className="primary" disabled={busy||needsRefresh||decision==="conditional_go"&&stage.waivableItems.length===0}>{decision==="reopen"?"Reopen readiness":"Record decision"}</button></form>:<p className="readiness-authority">A member assigned the accountable role or reviewer role must record this decision.</p>}
      {stage.history.length>0&&<details className="decision-history"><summary>Decision history ({stage.history.length})</summary><ol>{stage.history.map(entry=><li key={entry.id}><div><strong>{decisionLabel[entry.decision]}</strong><span className={entry.effective?"current":"stale"}>{entry.effective?"Current":"Superseded or underlying work changed"}</span></div><p>{entry.rationale}</p><small>{entry.actorName} · {new Date(entry.createdAt).toLocaleString()}</small>{entry.exceptions.length>0&&<ul>{entry.exceptions.map(exception=><li key={exception.itemId}>{exception.rationale} — {exception.ownerName}, due {exception.dueDate}</li>)}</ul>}</li>)}</ol></details>}
    </div>})}
  </section>;
}


